In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('iris.csv')

In [3]:
df.rename(columns={
    "Type": "Plant Class",
    "PW": "Petal Width",
    "PL": "Petal Length",
    "SW": "Sepal Width",
    "SL": "Sepal Length"
})

     Plant Class  Petal Width  Petal Length  Sepal Width  Sepal Length
0              0            2            14           33            50
1              1           24            56           31            67
2              1           23            51           31            69
3              0            2            10           36            46
4              1           20            52           30            65
..           ...          ...           ...          ...           ...
145            1           20            50           25            57
146            2           13            40           23            55
147            0            2            17           34            54
148            1           24            51           28            58
149            0            2            15           37            53

[150 rows x 5 columns]

In [4]:
df[(df['PW'] > 10) & (df['PL'] > 50)]

     Type  PW  PL  SW  SL
1       1  24  56  31  67
2       1  23  51  31  69
4       1  20  52  30  65
5       1  19  51  27  58
19      1  21  56  28  64
25      1  19  51  27  58
27      1  18  55  31  64
34      1  23  57  32  69
37      1  18  58  25  67
41      1  21  54  31  69
42      1  25  61  36  72
44      1  21  55  30  68
50      1  22  56  28  64
51      1  15  51  28  63
55      1  23  59  32  68
56      1  23  54  34  62
57      1  25  57  33  67
60      1  18  51  30  59
61      1  23  53  32  64
63      1  21  57  33  67
66      1  18  60  32  72
74      1  23  61  30  77
84      2  13  54  29  62
92      1  20  51  32  65
99      1  25  60  33  63
103     2  16  51  27  60
104     1  18  55  30  65
106     1  22  67  38  77
107     1  21  66  30  76
108     1  13  52  30  67
112     1  20  64  38  79
114     1  20  67  28  77
118     1  14  56  26  61
124     1  24  56  34  63
125     1  16  58  30  72
126     1  21  59  30  71
127     1  18  56  29  63
129     1  23  69  26  77
130     2  13  56  29  66
134     1  19  61  28  74
136     1  18  63  29  73
140     1  22  58  30  65
143     1  19  53  27  64
148     1  24  51  28  58

In [5]:
df['Species'] = df['Type']
df

     Type  PW  PL  SW  SL  Species
0       0   2  14  33  50        0
1       1  24  56  31  67        1
2       1  23  51  31  69        1
3       0   2  10  36  46        0
4       1  20  52  30  65        1
..    ...  ..  ..  ..  ..      ...
145     1  20  50  25  57        1
146     2  13  40  23  55        2
147     0   2  17  34  54        0
148     1  24  51  28  58        1
149     0   2  15  37  53        0

[150 rows x 6 columns]

In [7]:
df.to_csv('/content/new_iris.csv')

In [13]:
df.groupby('Species')['PW'].agg(['min', 'max'])

         min  max
Species
0          1    6
1         13   25
2         10   18

In [10]:
df.shape

(150, 6)

In [12]:
df.describe()

             Type          PW          PL          SW          SL     Species
count  150.000000  150.000000  150.000000  150.000000  150.000000  150.000000
mean     1.000000   11.926667   37.786667   30.553333   58.446667    1.000000
std      0.819232    7.569008   17.776233    4.372791    8.268592    0.819232
min      0.000000    1.000000   10.000000   20.000000   43.000000    0.000000
25%      0.000000    3.000000   16.000000   28.000000   51.000000    0.000000
50%      1.000000   13.000000   44.000000   30.000000   58.000000    1.000000
75%      2.000000   18.000000   51.000000   33.000000   64.000000    2.000000
max      2.000000   25.000000   69.000000   44.000000   79.000000    2.000000

In [18]:
df['Species'].value_counts()

Species
0    50
1    50
2    50
Name: count, dtype: int64

In [20]:
new_dataset=df[df['Species']=='iris-setosa']