In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('contact-lenses.csv')

In [3]:
df.head()

     age spectacle_prescrip astigmatism tear_prod_rate contact_lenses
0  young              myope          no        reduced           none
1  young              myope          no         normal           soft
2  young              myope         yes        reduced           none
3  young              myope         yes         normal           hard
4  young       hypermetrope          no        reduced           none

In [4]:
df.tail(3)

           age spectacle_prescrip astigmatism tear_prod_rate contact_lenses
21  presbyopic       hypermetrope          no         normal           soft
22  presbyopic       hypermetrope         yes        reduced           none
23  presbyopic       hypermetrope         yes         normal           none

In [5]:
df.columns
df.dtypes

age                   object
spectacle_prescrip    object
astigmatism           object
tear_prod_rate        object
contact_lenses        object
dtype: object

In [6]:
df['age'].value_counts()

age
young             8
pre-presbyopic    8
presbyopic        8
Name: count, dtype: int64

In [8]:
df.describe()

          age spectacle_prescrip astigmatism tear_prod_rate contact_lenses
count      24                 24          24             24             24
unique      3                  2           2              2              3
top     young              myope          no        reduced           none
freq        8                 12          12             12             15

In [13]:
df.loc[2]

age                     young
spectacle_prescrip      myope
astigmatism               yes
tear_prod_rate        reduced
contact_lenses           none
Name: 2, dtype: object

In [14]:
df.iloc[3,1]

'myope'

In [15]:
df[df['astigmatism'].str.contains('no')]

,age,spectacle_prescrip,astigmatism,tear_prod_rate,contact_lenses
0,young,myope,no,reduced,none
1,young,myope,no,normal,soft
4,young,hypermetrope,no,reduced,none
5,young,hypermetrope,no,normal,soft
8,pre-presbyopic,myope,no,reduced,none
9,pre-presbyopic,myope,no,normal,soft
12,pre-presbyopic,hypermetrope,no,reduced,none
13,pre-presbyopic,hypermetrope,no,normal,soft
16,presbyopic,myope,no,reduced,none
17,presbyopic,myope,no,normal,none
20,presbyopic,hypermetrope,no,reduced,none
21,presbyopic,hypermetrope,no,normal,soft

In [16]:
df[(df['age'].str.contains('young')) & (df['contact_lenses'].str.contains('soft'))]

     age spectacle_prescrip astigmatism tear_prod_rate contact_lenses
1  young              myope          no         normal           soft
5  young       hypermetrope          no         normal           soft

In [17]:
df.shape

(24, 5)

In [18]:
df.sort_values(by='astigmatism', ascending=False)

,age,spectacle_prescrip,astigmatism,tear_prod_rate,contact_lenses
23,presbyopic,hypermetrope,yes,normal,none
2,young,myope,yes,reduced,none
3,young,myope,yes,normal,hard
22,presbyopic,hypermetrope,yes,reduced,none
6,young,hypermetrope,yes,reduced,none
7,young,hypermetrope,yes,normal,hard
19,presbyopic,myope,yes,normal,hard
10,pre-presbyopic,myope,yes,reduced,none
11,pre-presbyopic,myope,yes,normal,hard
18,presbyopic,myope,yes,reduced,none
14,pre-presbyopic,hypermetrope,yes,reduced,none
15,pre-presbyopic,hypermetrope,yes,normal,none
16,presbyopic,myope,no,reduced,none
21,presbyopic,hypermetrope,no,normal,soft
20,presbyopic,hypermetrope,no,reduced,none
17,presbyopic,myope,no,normal,none
0,young,myope,no,reduced,none
13,pre-presbyopic,hypermetrope,no,normal,soft
1,young,myope,no,normal,soft
9,pre-presbyopic,myope,no,normal,soft
8,pre-presbyopic,myope,no,reduced,none
5,young,hypermetrope,no,normal,soft
4,young,hypermetrope,no,reduced,none
12,pre-presbyopic,hypermetrope,no,reduced,none

In [19]:
df = df.iloc[2:5]
df[df['astigmatism'].str.contains('no')]

     age spectacle_prescrip astigmatism tear_prod_rate contact_lenses
4  young       hypermetrope          no        reduced           none