**Start by doing the following**



1.   Go to your [lab2](https://moodle.bcu.ac.uk/mod/folder/view.php?id=8931483) on your Moodle. Download the dataset 'rollingsales_bronx.xls' from moodle and upload it in your colab
2.   Download the Lab Example notebook and upload in your Google Drive and open it beside this one.
3.   Check each relevant section in the example noteobook to be able to answer the questions below

# **Exercise 1 for Lab 2**

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_excel("/content/rollingsales_bronx.xlsx")

In [ ]:
#we read the data in again but skip 4 rows this time, then take row [0] after cleaning as header
df = pd.read_excel("/content/rollingsales_bronx.xlsx", skiprows = 4, header = [0])

df.head()

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASEMENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,2,BATHGATE,NaN,1,2907,24,NaN,A1,4090 PARK AVENUE,NaN,...,1.0,0.0,1.0,2500.0,1474.0,1901.0,1,A1,0,2024-03-28
1,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3046,27,NaN,A1,2090 WASHINGTON AVENUE,NaN,...,1.0,0.0,1.0,2356.0,2213.0,NaN,1,A1,0,2024-06-11
2,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3046,40,NaN,A1,2073 BATHGATE AVENUE,NaN,...,1.0,0.0,1.0,1933.0,1344.0,NaN,1,A1,425000,2024-06-27
3,2,BATHGATE,NaN,1,3047,11,NaN,A1,482 EAST 181ST STREET,NaN,...,1.0,0.0,1.0,1556.0,1240.0,1901.0,1,A1,0,2024-06-14
4,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3050,91,NaN,A9,503 EAST 182 STREET,NaN,...,1.0,0.0,1.0,1960.0,1705.0,NaN,1,A9,515000,2024-04-11

## **1. Clean the dataset header and rename columns as in the lab example (Hint check Section 1. Data Cleaning in Lab2 Example).**

In [ ]:
#Extract columns
cols=df.columns
#Create empty list
new_cols=[]
#iterate to fix issues with names
for column in cols:
  #to proper case
  proper_cols=column.title()
  #replace space/hypen with underscore
  proper_cols_hypen=proper_cols.replace("","_")
  clean_col=proper_cols_hypen.replace("-","_")
  #append to empty list
  new_cols.append(clean_col)

# #replace existing columns in dataframe with new
df.columns=new_cols
#preview
df.head()

,_B_o_r_o_u_g_h_,_N_e_i_g_h_b_o_r_h_o_o_d_,_B_u_i_l_d_i_n_g_ _C_l_a_s_s_ _C_a_t_e_g_o_r_y_,_T_a_x_ _C_l_a_s_s_ _A_t_ _P_r_e_s_e_n_t_,_B_l_o_c_k_,_L_o_t_,_E_a_s_e_m_e_n_t_,_B_u_i_l_d_i_n_g_ _C_l_a_s_s_ _A_t_ _P_r_e_s_e_n_t_,_A_d_d_r_e_s_s_,_A_p_a_r_t_m_e_n_t_ _N_u_m_b_e_r_,...,_R_e_s_i_d_e_n_t_i_a_l_ _U_n_i_t_s_,_C_o_m_m_e_r_c_i_a_l_ _U_n_i_t_s_,_T_o_t_a_l_ _U_n_i_t_s_,_L_a_n_d_ _S_q_u_a_r_e_ _F_e_e_t_,_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_,_Y_e_a_r_ _B_u_i_l_t_,_T_a_x_ _C_l_a_s_s_ _A_t_ _T_i_m_e_ _O_f_ _S_a_l_e_,_B_u_i_l_d_i_n_g_ _C_l_a_s_s_ _A_t_ _T_i_m_e_ _O_f_ _S_a_l_e_,_S_a_l_e_ _P_r_i_c_e_,_S_a_l_e_ _D_a_t_e_
0,2,BATHGATE,NaN,1,2907,24,NaN,A1,4090 PARK AVENUE,NaN,...,1.0,0.0,1.0,2500.0,1474.0,1901.0,1,A1,0,2024-03-28
1,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3046,27,NaN,A1,2090 WASHINGTON AVENUE,NaN,...,1.0,0.0,1.0,2356.0,2213.0,NaN,1,A1,0,2024-06-11
2,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3046,40,NaN,A1,2073 BATHGATE AVENUE,NaN,...,1.0,0.0,1.0,1933.0,1344.0,NaN,1,A1,425000,2024-06-27
3,2,BATHGATE,NaN,1,3047,11,NaN,A1,482 EAST 181ST STREET,NaN,...,1.0,0.0,1.0,1556.0,1240.0,1901.0,1,A1,0,2024-06-14
4,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3050,91,NaN,A9,503 EAST 182 STREET,NaN,...,1.0,0.0,1.0,1960.0,1705.0,NaN,1,A9,515000,2024-04-11

## **2. Check missing data (Hint check  Section 2 Missing Data  in the Lab2 Example):**
  **A. check missing data in the whole dataset**

  **B. Fill in the missing data in **Total_Units** column with the appropriate value based on your analysis**

In [ ]:
#Check missing data by checking how many nulls

df.isnull().sum()

_B_o_r_o_u_g_h_                                                     0
_N_e_i_g_h_b_o_r_h_o_o_d_                                           0
_B_u_i_l_d_i_n_g_ _C_l_a_s_s_ _C_a_t_e_g_o_r_y_                     2
_T_a_x_ _C_l_a_s_s_ _A_t_ _P_r_e_s_e_n_t_                           0
_B_l_o_c_k_                                                         0
_L_o_t_                                                             0
_E_a_s_e_m_e_n_t_                                                5718
_B_u_i_l_d_i_n_g_ _C_l_a_s_s_ _A_t_ _P_r_e_s_e_n_t_                 0
_A_d_d_r_e_s_s_                                                     0
_A_p_a_r_t_m_e_n_t_ _N_u_m_b_e_r_                                5197
_Z_i_p_ _C_o_d_e_                                                   0
_R_e_s_i_d_e_n_t_i_a_l_ _U_n_i_t_s_                              1127
_C_o_m_m_e_r_c_i_a_l_ _U_n_i_t_s_                                1603
_T_o_t_a_l_ _U_n_i_t_s_                                          1100
_L_a_n_d_ _S_q_u_a_r_e_ _F_e_e_t_                                1630
_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_                              1630
_Y_e_a_r_ _B_u_i_l_t_                                             619
_T_a_x_ _C_l_a_s_s_ _A_t_ _T_i_m_e_ _O_f_ _S_a_l_e_                 0
_B_u_i_l_d_i_n_g_ _C_l_a_s_s_ _A_t_ _T_i_m_e_ _O_f_ _S_a_l_e_       0
_S_a_l_e_ _P_r_i_c_e_                                               0
_S_a_l_e_ _D_a_t_e_                                                 0
dtype: int64

In [ ]:
#Check how many nulls in the Total_Units column

df['_T_o_t_a_l_ _U_n_i_t_s_'].isnull().sum()

np.int64(1100)

In [ ]:
#Check skewdness for this column

print("skewness",df['_T_o_t_a_l_ _U_n_i_t_s_'].skew())

skewness 12.648391266422264

**Give your interpretation of the results**




1.   List item
2.   List item

In [ ]:
print("Mean",df['_T_o_t_a_l_ _U_n_i_t_s_'].mean())
print("Median",df['_T_o_t_a_l_ _U_n_i_t_s_'].median())
print("Mode",df['_T_o_t_a_l_ _U_n_i_t_s_'].mode())

Mean 3.631875270679948
Median 2.0
Mode 0    1.0
Name: _T_o_t_a_l_ _U_n_i_t_s_, dtype: float64

median is better here, because:

median: it is robust to outliers and better reflects the central tendency in skewed distributions.

Avoid: Mean: it would be inflated bt the high-end outliers

Avoid: Mode: if values are mostly 1 or 2 only.

In [ ]:
# You can now fill the Total_Units with your chosen method.

median_units=df['_T_o_t_a_l_ _U_n_i_t_s_'].median()
df['_T_o_t_a_l_ _U_n_i_t_s_'].fillna(median_units)

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
5713    2.0
5714    2.0
5715    2.0
5716    2.0
5717    9.0
Name: _T_o_t_a_l_ _U_n_i_t_s_, Length: 5718, dtype: float64

In [ ]:
# Now check if there are missing values for Total_Units
df['_T_o_t_a_l_ _U_n_i_t_s_'].isnull().sum()

np.int64(0)

## **3. Check the mean, mode, median and standard deviation of the Sale_Price column**

In [ ]:
# print each one in a seperate line

print("Mean:",df['_S_a_l_e_ _P_r_i_c_e_'].mean())
print("Median:",df['_S_a_l_e_ _P_r_i_c_e_'].median())
print("Mode:",df['_S_a_l_e_ _P_r_i_c_e_'].mode())
print("Standard Deviation:",df['_S_a_l_e_ _P_r_i_c_e_'].std())

Mean: 673315.9783140959
Median: 295000.0
Mode: 0    0
Name: _S_a_l_e_ _P_r_i_c_e_, dtype: int64
Standard Deviation: 1515792.5640463387

## **4. Standarise the Gross_Square_Feet colum with the StandardScaler(). Fill in missing values first then standardise (Hint check Section 3: Data Scaling  in the lab example)**

In [ ]:
#First check if it has missing values
df['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_'].isnull().sum()

np.int64(1630)

In [ ]:
print("Mean:",df['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_'].mean())
print("Median:",df['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_'].median())
print("Mode:",df['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_'].mode())
print("Standard Deviation:",df['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_'].std())

Mean: 6614.758806262231
Median: 2177.0
Mode: 0    0.0
Name: _G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_, dtype: float64
Standard Deviation: 51019.88302172309

In [ ]:
#Fill the missing vallues with the a chosen method as in exercise 2 above
median_units=df['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_'].median()
df['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_'].fillna(median_units)

0       1474.0
1       2213.0
2       1344.0
3       1240.0
4       1705.0
         ...
5713    2177.0
5714    2177.0
5715    2177.0
5716    2177.0
5717    8556.0
Name: _G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_, Length: 5718, dtype: float64

In [ ]:
# You can now fill the missing value with your chosen method
median_units=df['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_'].median()
df['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_'].fillna(median_units)

0       1474.0
1       2213.0
2       1344.0
3       1240.0
4       1705.0
         ...
5713    2177.0
5714    2177.0
5715    2177.0
5716    2177.0
5717    8556.0
Name: _G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_, Length: 5718, dtype: float64

In [ ]:
# check if you cleaned all missing values from Gross_Square_Feet
df['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_'].isnull().sum()

np.int64(1630)

In [ ]:
# Extract min and max for Gross_Square_Feet
Gross_Square_Feet_min =df['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_'].min()

Gross_Square_Feet_max =df['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_'].max()



# Display the comparison

print(f"Gross Square Feet Range: {Gross_Square_Feet_min :,.2f} to {Gross_Square_Feet_max :,.2f} sq ft")

Gross Square Feet Range: 0.00 to 1,172,005.00 sq ft

**Write your interpretation of the range**

In [ ]:
import pandas
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

from sklearn.preprocessing import StandardScaler
import pandas as pd

# Select and scale
X = df[['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_']]
# define your scaler
scaler = StandardScaler()
#transform your data
scaledX=scaler.fit_transform(X)
# Scale the data
scaledX = scaler.fit_transform(X)



#Now let's see the values after scaling (the mean should be 0 and standard deviation 1)
# Convert back to DataFrame
scaled_df = pd.DataFrame(scaledX, columns=['_G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_'])



# Print mean and std of scaled columns
print("Mean values:\n", scaled_df.mean())
print("\nStandard deviation values:\n", scaled_df.std())

Mean values:
 _G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_    1.390495e-17
dtype: float64

Standard deviation values:
 _G_r_o_s_s_ _S_q_u_a_r_e_ _F_e_e_t_    1.000122
dtype: float64

## **5. Impute the Building_Class_Category with a Lable Encoder (Hint check Section 4 Imputing Categorical Data in Lab example)**

In [ ]:
# Check the values of the Building_Class_Category
df['_B_u_i_l_d_i_n_g_ _C_l_a_s_s_ _C_a_t_e_g_o_r_y_'].value_counts()

_B_u_i_l_d_i_n_g_ _C_l_a_s_s_ _C_a_t_e_g_o_r_y_
02 TWO FAMILY DWELLINGS                      1485
01 ONE FAMILY DWELLINGS                      1129
10 COOPS - ELEVATOR APARTMENTS                994
03 THREE FAMILY DWELLINGS                     627
13 CONDOS - ELEVATOR APARTMENTS               339
07 RENTALS - WALKUP APARTMENTS                250
05 TAX CLASS 1 VACANT LAND                    164
04 TAX CLASS 1 CONDOS                         134
29 COMMERCIAL GARAGES                          98
22 STORE BUILDINGS                             93
08 RENTALS - ELEVATOR APARTMENTS               73
09 COOPS - WALKUP APARTMENTS                   68
06 TAX CLASS 1 - OTHER                         36
31 COMMERCIAL VACANT LAND                      34
14 RENTALS - 4-10 UNIT                         31
30 WAREHOUSES                                  31
12 CONDOS - WALKUP APARTMENTS                  28
21 OFFICE BUILDINGS                            17
41 TAX CLASS 4 - OTHER                         15
44 CONDO PARKING                               14
37 RELIGIOUS FACILITIES                        11
27 FACTORIES                                    8
32 HOSPITAL AND HEALTH FACILITIES               5
46 CONDO STORE BUILDINGS                        5
17 CONDO COOPS                                  5
26 OTHER HOTELS                                 4
43 CONDO OFFICE BUILDINGS                       3
33 EDUCATIONAL FACILITIES                       2
38 ASYLUMS AND HOMES                            2
35 INDOOR PUBLIC AND CULTURAL FACILITIES        2
47 CONDO NON-BUSINESS STORAGE                   2
11 SPECIAL CONDO BILLING LOTS                   2
28 COMMERCIAL CONDOS                            2
15 CONDOS - 2-10 UNIT RESIDENTIAL               2
42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC       1
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Initialize encoder
le=LabelEncoder()

# Fit and transform

df['_B_u_i_l_d_i_n_g_ _C_l_a_s_s_ _C_a_t_e_g_o_r_y_']=le.fit_transform(df['_B_u_i_l_d_i_n_g_ _C_l_a_s_s_ _C_a_t_e_g_o_r_y_'])

# View mapping
label_mapping=dict(zip(le.classes_,le.transform(le.classes_)))
print("Label Mapping:\n", label_mapping)

Label Mapping:
 {'01 ONE FAMILY DWELLINGS': np.int64(0), '02 TWO FAMILY DWELLINGS': np.int64(1), '03 THREE FAMILY DWELLINGS': np.int64(2), '04 TAX CLASS 1 CONDOS': np.int64(3), '05 TAX CLASS 1 VACANT LAND': np.int64(4), '06 TAX CLASS 1 - OTHER': np.int64(5), '07 RENTALS - WALKUP APARTMENTS': np.int64(6), '08 RENTALS - ELEVATOR APARTMENTS': np.int64(7), '09 COOPS - WALKUP APARTMENTS': np.int64(8), '10 COOPS - ELEVATOR APARTMENTS': np.int64(9), '11 SPECIAL CONDO BILLING LOTS': np.int64(10), '12 CONDOS - WALKUP APARTMENTS': np.int64(11), '13 CONDOS - ELEVATOR APARTMENTS': np.int64(12), '14 RENTALS - 4-10 UNIT': np.int64(13), '15 CONDOS - 2-10 UNIT RESIDENTIAL': np.int64(14), '17 CONDO COOPS': np.int64(15), '21 OFFICE BUILDINGS': np.int64(16), '22 STORE BUILDINGS': np.int64(17), '26 OTHER HOTELS': np.int64(18), '27 FACTORIES': np.int64(19), '28 COMMERCIAL CONDOS': np.int64(20), '29 COMMERCIAL GARAGES': np.int64(21), '30 WAREHOUSES': np.int64(22), '31 COMMERCIAL VACANT LAND': np.int64(23), '32 HOSPITAL AND HEALTH FACILITIES': np.int64(24), '33 EDUCATIONAL FACILITIES': np.int64(25), '35 INDOOR PUBLIC AND CULTURAL FACILITIES': np.int64(26), '37 RELIGIOUS FACILITIES': np.int64(27), '38 ASYLUMS AND HOMES': np.int64(28), '41 TAX CLASS 4 - OTHER': np.int64(29), '42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC': np.int64(30), '43 CONDO OFFICE BUILDINGS': np.int64(31), '44 CONDO PARKING': np.int64(32), '46 CONDO STORE BUILDINGS': np.int64(33), '47 CONDO NON-BUSINESS STORAGE': np.int64(34), nan: np.int64(35)}